import { createClient } from "@/prismicio";
import { SliceZone } from "@prismicio/react";

import { components } from '../../slices'

export default async function Investigacion() {
    const client = createClient();

    const page = await client.getByUID('page','investigacion')

    return (
        <>
            <main>
                <SliceZone slices={page.data.slices} components={components} />
            </main>
        </>
    );
    }
    // return (
    //     <>
    //         <Head>
    //             <title>Create Next App</title>
    //             <meta name="description" content="Generated by create next app" />
    //             <meta name="viewport" content="width=device-width, initial-scale=1" />
    //             <link rel="icon" href="/favicon.ico" />
    //         </Head>
    //         <main>
    //             <section className="bg-[#3E5E75] text-[#F0F0F0]">
    //                 <div className="container mx-auto px-6 py-16">
    //                     <h2 className="text-center lg:text-6xl text-4xl font-semibold">
    //                         Investigación
    //                     </h2>
    //                 </div>
    //             </section>
    //             <section className="text-[#3E5E75] bg-[#F0F0F0] pb-24">
    //                 <div className="container mx-auto px-6 py-6">
    //                     <h4 className="text-center lg:text-5xl text-3xl my-16 font-light">
    //                         Proyectos
    //                     </h4>
    //                     <div className="grid lg:grid-cols-4 mt-8 place-items-center">
    //                         <div className="h-[284px] w-[232px] mb-8 rounded-lg drop-shadow-lg bg-white transform transition duration-500 hover:scale-105">
    //                             <a
    //                                 href="https://halley.uis.edu.co/fuego/"
    //                                 target="_blank"
    //                                 rel="noreferrer"
    //                             >
    //                                 <div>
    //                                     <div className="p-4">
    //                                         <Image
    //                                             src="/images/mute.jpg"
    //                                             alt="mute"
    //                                             width={200}
    //                                             height={200}
    //                                             className="h-[216px] w-[205px] object-contain"
    //                                         />
    //                                     </div>
    //                                 </div>
    //                                 <div>
    //                                     <h3 className="ml-4 text-2xl font-semibold">MuTe</h3>
    //                                 </div>
    //                             </a>
    //                         </div>
    //                         <div className="h-[284px] w-[232px] mb-8 rounded-lg drop-shadow-lg bg-white transform transition duration-500 hover:scale-105">
    //                             <Link
    //                                 href="https://lagoproject.net/"
    //                                 target="_blank"
    //                                 rel="noreferrer"
    //                             >
    //                                 <div>
    //                                     <div className="p-4">
    //                                         <Image
    //                                             src="/images/lago-logo.png"
    //                                             alt="lago"
    //                                             width={200}
    //                                             height={200}
    //                                             className="h-[216px] w-[205px] object-contain"
    //                                         />
    //                                     </div>
    //                                 </div>
    //                                 <div>
    //                                     <h3 className="ml-4 text-2xl font-semibold">Lago-UIS</h3>
    //                                 </div>
    //                             </Link>
    //                         </div>
    //                         <div className="h-[284px] w-[232px] mb-8 rounded-lg drop-shadow-lg bg-white transform transition duration-500 hover:scale-105">
    //                             <a
    //                                 href="http://auger.uis.edu.co/"
    //                                 target="_blank"
    //                                 rel="noreferrer"
    //                             >
    //                                 <div>
    //                                     <div className="p-4">
    //                                         <Image
    //                                             src="/images/auger_logo.jpg"
    //                                             alt="auger"
    //                                             width={200}
    //                                             height={200}
    //                                             className="h-[216px] w-[205px] object-contain"
    //                                         />
    //                                     </div>
    //                                 </div>
    //                                 <div>
    //                                     <h3 className="ml-4 text-2xl font-semibold">Auger-UIS</h3>
    //                                 </div>
    //                             </a>
    //                         </div>
    //                         <div className="h-[284px] w-[232px] mb-8 rounded-lg drop-shadow-lg bg-white transform transition duration-500 hover:scale-105">
    //                             <Link
    //                                 href="https://halley.uis.edu.co/astroparamo/"
    //                                 target="_blank"
    //                             >
    //                                 <div>
    //                                     <div className="p-4">
    //                                         <Image
    //                                             src="/images/astroparamo.png"
    //                                             alt="astroparamo"
    //                                             width={200}
    //                                             height={200}
    //                                             className="h-[216px] w-[205px] object-contain"
    //                                         />
    //                                     </div>
    //                                 </div>
    //                                 <div>
    //                                     <h3 className="ml-4 text-2xl font-semibold">Astropáramo</h3>
    //                                 </div>
    //                             </Link>
    //                         </div>
    //                     </div>
    //                 </div>
    //             </section>
    //         </main>
    //     </>
    // );