// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog: dynamic(() => import("./Blog")),
  divulgacion: dynamic(() => import("./Divulgacion")),
  hero: dynamic(() => import("./Hero")),
  investigacion: dynamic(() => import("./Investigacion")),
};
